apiVersion: v1
entries:
  ingress-azure:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-12-12T16:38:16.5059209+13:00
    description: Use Azure Application Gateway as the ingress for an Azure Kubernetes
      Service cluster.
    digest: b64f9b3de1249fb276af5d9d70ab299a25a1f98657338677347c4010a076c587
    name: ingress-azure
    urls:
    - ingress-azure-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-12-12T16:38:16.5059209+13:00
    description: Use Azure Application Gateway as the ingress for an Azure Kubernetes
      Service cluster.
    digest: 1255b1c15cca79c7ec722eeb338de202ee66e431c8790ed55108ffad4af4bbd9
    name: ingress-azure
    urls:
    - ingress-azure-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-12-12T16:38:16.5049215+13:00
    description: Use Azure Application Gateway as the ingress for an Azure Kubernetes
      Service cluster.
    digest: 39cc6e0c535835667fd26f609a56daf32d31f6a256811a93ee04e265b1bb7216
    name: ingress-azure
    urls:
    - ingress-azure-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v1
    appVersion: "1.0"
    created: 2018-12-12T16:38:16.5049215+13:00
    description: Use Azure Application Gateway as the ingress for an Azure Kubernetes
      Service cluster.
    digest: 643f5b99c847952108e781ce746f27bed55b248a002ee04b6b6ca3f0b51320ba
    name: ingress-azure
    urls:
    - ingress-azure-0.1.3.tgz
    version: 0.1.3
generated: 2018-12-12T16:38:16.503924+13:00
